\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\contentsline {lstlisting}{\numberline {3.1}R.java}{10}{lstlisting.31}
\contentsline {lstlisting}{\numberline {3.2}MainActivity.java}{10}{lstlisting.44}
\contentsline {lstlisting}{\numberline {3.3}strings.xml}{12}{lstlisting.60}
\contentsline {lstlisting}{\numberline {3.4}AndroidManifest.xml}{13}{lstlisting.71}
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
